apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment    # Updated to match rollout status command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: prajnashetty529/register-app:latest
          ports:
            - containerPort: 8080
